### ISSUE TITLE
请问一下如何配置默认参数？

### ISSUE THREAD

**Issue by syanbo** [yingye/wepy-plugin-px2units#2]
我在 wepy.config.js
  plugins: {
    'px2units': {
      filter: /\.wxss$/,
      comment: 'no less',
      multiple: 2
    }
  }
这样写 multiple 和 comment  没有效果。

**Comment by yingye** [comment]
通过这样配置来添加config：
```js
plugins: {
  'px2units': {
    filter: /\.wxss$/,
    config: {
      comment: 'less',
      multiple: 2
    }
  }
}
```
由于 WePY 在走 plugin 之前，会把 comment 都移除，所以导致该 plugin 接受不到 comment 参数。之前有给 WePY 提过关于 postcss 的 PR，但是一直没有采纳。目前可以采用行内样式等 hack 的方式。

**Comment by syanbo** [comment]
可以了 优秀优秀
