### ISSUE TITLE
请问怎么忽略某一个css属性的编译

### ISSUE THREAD

**Issue by Cyran777** [yingye/wepy-plugin-px2units#3]
测试在属性后加 /* no \*/ 和  /\* px  */，都不管用 
@yingye

**Comment by yingye** [comment]
由于 WePY 在走 plugin 之前，会把 comment 都移除，所以导致该 plugin 接受不到 comment 参数。之前有给 WePY 提过关于 postcss 的 PR，但是一直没有采纳。目前可以采用行内样式等 hack 的方式。

**Comment by Cyran777** [comment]
好吧，期待这个问题的改进，功能还是很好用的
