### ISSUE TITLE
请问能增加一个exclude的配置项吗?

### ISSUE THREAD

**Issue by Undrum** [yingye/wepy-plugin-px2units#4]
RT

**Comment by yingye** [comment]
麻烦详细描述一下呗

**Comment by Undrum** [comment]
在配置参数里面增加一个exclude的配置项支持正则表达式，忽略符合条件目录下的wxss文件。

**Comment by yingye** [comment]
能否在插件定义时 filter 中实现？

**Comment by Undrum** [comment]
我提交了一个PR，我现在也是这样解决的。

**Comment by yingye** [comment]
两个正则不能合成一个正则嘛？

**Comment by Undrum** [comment]
可以是可以，但是正则写起来略显复杂。不如这样增加一个配置项来得清晰。

**Comment by yingye** [comment]
建议还是写在一起吧 : )

**Comment by Undrum** [comment]
好吧！

**Comment by yingye** [comment]
比如，忽略 `abc.wxss` 文件，正则表达式可以这样写：`/(?<!\/abc)\.wxss$/i`
