### ISSUE TITLE
拷贝wxss的时候op.code是空的

### ISSUE THREAD

**Issue by jardenliu** [yingye/wepy-plugin-px2units#6]
```javascript
 prefixer.process(op.code, { from: op.file }).then((result) => {
```
我在src下面了放了一些第三方的小程序组件，wepy会把里面的文件夹拷贝到dist下面。
使用px2units的时候，也希望把第三方组件里面的px改成rpx。
build的时候还会提示
```bash
     [WARNING] Error: PostCSS received null instead of CSS string
```

可否添加判断op.code为空的时候  用fs读取op.file的文件内容

**Comment by yingye** [comment]
“第三方的小程序组件”应该是编译之后的代码，而不应该在这个项目中再编译一次啊。

**Comment by jardenliu** [comment]
第三方组件是用px的，这个组件不可以支持再转换？
