### ISSUE TITLE
关于base64的值被转换rpx问题

### ISSUE THREAD

**Issue by Cyran777** [yingye/wepy-plugin-px2units#7]
小程序添加的第三方字体库，类似iconfont，转成base64后，因为值含有px字母被转义rpx，导致字体失效，有没有配置信息能修改的，忽略掉指定的wxss

**Comment by yingye** [comment]
升级至 v1.1.0 版本，解决该问题，谢谢～

**Comment by yingye** [comment]
这个issue可以分成两部分：
1. 【将非单位px转换成了rpx】postcss-px2units 中正则判断问题，升级版本即可
2. 【忽略掉指定的wxss】例如，忽略 `abc.wxss` 文件，正则表达式可以这样写：`/(?<!\/abc)\.wxss$/i`
