### ISSUE TITLE
请问 支持 wepy2.x 吗？

### ISSUE THREAD

**Issue by huangyilu** [yingye/wepy-plugin-px2units#8]

**Comment by linshuzhen** [comment]
同问，搞半天了一直不行，是不是不支持呀

**Comment by rzp1** [comment]
同问

**Comment by chenchaoc** [comment]
同问，插件改成函数了，能不能搞个2.0的

**Comment by chenchaoc** [comment]
作者是摩拜公司的，不会被美团收购财富自由畅游世界去了吧~~

**Comment by yingye** [comment]
本插件不支持 wepy 2.x 版本哈，因为新的版本已经支持 postcss 插件了，文档地址：https://wepyjs.github.io/wepy-docs/2.x/#/plugin/official?id=compiler-postcss

wepy 2.x 版本可以直接使用：[postcss-px2units](https://github.com/yingye/postcss-px2units) 插件了。
